quarkus:
  http:
    test-timeout: 60s
  console:
    color: true
  keycloak:
    devservices:
      realm-path: agate-realm.json
      start-timeout: 300s
  #  cxf:
  #    client:
  #      uid:
  #        http-conduit-factory: URLConnectionHTTPConduitFactory
  #        client-endpoint-url: http://localhost:8051/uid-register/findByUid
  #  flyway:
  #    locations:
  #      - classpath:db/migration
  #      - classpath:db/testdata

  log:
    level: WARN
    category:
      ch.agridata.common.filters:
        level: WARN
#  oidc-client:
#    agis-api:
#      token-path: http://localhost:8051/agate/token
#  rest-client:
#    agis-register-api:
#      url: http://localhost:8051/agis/register-data/1
#
#  wiremock:
#    devservices:
#      enabled: true
#      files-mapping: src/test/resources/wiremock
#      port: 8051
#      reload: true
