atlas:
  exception-handling:
    return-debug: false
quarkus:
  application:
    name: "Agate test backend"
  banner:
    path: banner.txt
  cxf:
    codegen:
      wsdl2java:
        nevis:
          includes: wsdl/nevis_api.wsdl
          package-names: ch.blw.agate.user.soap.generated
          additional-params:
            - -b
            - src/main/resources/wsdl/bindings.xjb
    client:
      adminService:
        client-endpoint-url: ${SOAP_ENDPOINT_URL:https://backend.blw-agate-dev.pc-core.isceco.admin.ch/backend/soap/AdminService/v1_44}
        service-interface: ch.blw.agate.user.soap.generated.AdminService
        out-interceptors: "#bearerTokenInterceptor"
  #  datasource:
  #    db-kind: postgresql
  #    jdbc:
  #      driver: org.postgresql.Driver
  #  flyway:
  #    baseline-on-migrate: true
  #    locations:
  #      - classpath:db/migration
  #    migrate-at-start: true
  #  hibernate-orm:
  #    mapping:
  #      format:
  #        global: ignore # See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.26#jackson-based-json-serialization
  http:
    root-path: /test-backend
    auth:
      permission:
        api-protected:
          paths: api/*
          policy: authenticated
          methods: GET,POST,PUT,DELETE,PATCH
        api-options:
          paths: api/*
          methods: OPTIONS
          policy: permit
          auth-mechanism: none
        unprotected:
          paths: q/*
          policy: permit
          auth-mechanism: none
    cors:
      access-control-allow-credentials: true
      enabled: true
      headers:
        - Authorization
        - Content-Type
        - X-Requested-With
      methods:
        - GET
        - PUT
        - POST
        - DELETE
        - OPTIONS
        - PATCH
    port: 8900
  micrometer:
    enabled: true
    binder:
      jvm: true
      system: true
      http-server:
        enabled: true

  log:
    category:
      "ch.blw.agate.common.filters":
        min-level: TRACE
    console:
      json:
        enabled: true
        pretty-print: false
      format: >-
        %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %s [%c] (%t) requestId: %X{requestId}, userId: %X{userId},  api: %X{api}%e%n
  oidc:
    authentication:
      pkce-required: true
      user-info-required: true
  # oidc-client:
  #    agis-api:
  #      grant:
  #        type: CLIENT
  #      refresh-token-time-skew: 1M # Refreshs the token one minute before it expires to avoid timing issues
  #  rest-client:
  #    agis-register-api:
  #      key-store-type: PKCS12
  #    agis-structure-api:
  #      key-store-type: PKCS12
  #    agis-eco-etho-api:
  #      key-store-type: PKCS12
  smallrye-openapi:
    info-description: This API provides access to the agate test application
    info-title: agate test API
    store-schema-directory: target/openapi
    store-schema-file-name: agate-test-api
  swagger-ui:
    theme: material
    always-include: true
    oauth-scopes: openid offline_access
    oauth-use-pkce-with-authorization-code-grant: true
    enabled: true
mp:
  openapi:
    scan:
      exclude:
        packages:
          - org.openapitools.api # excludes the automatically generated apis (e.g. AGIS) from the openapi documents
"%production":
  quarkus:
    oidc-client:
      auth-server-url: ${OIDC_CLIENT_AUTH_SERVER_URL:https://backend.blw-agate-dev.pc-core.isceco.admin.ch:8443/idp/realms/agate}
      client-id: agate-test-backend
      discovery-enabled: false
      token-path: /protocol/openid-connect/token
      jwks-path: /protocol/openid-connect/certs
      grant:
        type: client
      tls:
        tls-configuration-name: agate-mtls
    tls:
      agate-mtls:
        key-store:
          p12:
            path: ${MTLS_CLIENT_KEYSTORE_PATH:/deployments/certs/agate-client.p12}
            password: ${MTLS_CLIENT_KEYSTORE_PASSWORD}
