### get self
GET {{baseUrl}}/user/v1/user-info
Authorization: Bearer {{$auth.token("producer-a")}}
Content-Type: application/json

> {%
    client.test("Get producer users", function () {
        client.assert(response.status === 200, "Expected Response status is 200, got: " + response.status)
        client.assert(response.body !== null, "Expected Response results to contain products")
    })
%}

### get producers
GET {{baseUrl}}/user/v1/producers?size=10&page=0&sortBy=-lastLoginDate&searchTerm=smith john
Authorization: Bearer {{$auth.token("support")}}
Content-Type: application/json

> {%
    client.test("Get producer users", function () {
        client.assert(response.status === 200, "Expected Response status is 200, got: " + response.status)
        client.assert(response.body.items.length === 1, "Expected Response results to contain 1 item got: " + response.body.items.length)
    })
%}

### get authorized uids
GET {{baseUrl}}/user/v1/authorized-uids
Authorization: Bearer {{$auth.token("producer-a")}}
Content-Type: application/json

> {%
    client.test("Get producer users", function () {
        client.assert(response.status === 200, "Expected Response status is 200, got: " + response.status)
        client.assert(response.body !== null, "Expected Response results to contain products")
    })
%}

### set preferences
PUT {{baseUrl}}/user/v1/preferences
Authorization: Bearer {{$auth.token("producer-a")}}
Content-Type: application/json

{
  "mainMenuOpened": false,
  "activeUid": "123123",
  "dismissedMigratedIds": [
    "123123",
    "12312323"
  ]
}

> {%
    client.test("Get producer users", function () {
        client.assert(response.status === 201, "Expected Response status is 201, got: " + response.status)
    })
%}


